### PR TITLE
mavlink-api for interfacing with Pixhawk

### PR DESCRIPTION
**Pull request by lk-iqt**
Added mavlink-api for interfacing with Pixhwark hardware in utils/mavlink-api. This is seperated into a seperate utility container that can be spun up as needed.To run insure that the device is correctly mapped to the /dev/pixhawk_serial endooint or correctly specified in docker compose. 

Next run:
docker compose -f utils/mavlink-api/docker-compose.yml

### CODE REVIEW

**Review by anarkiwi — DISMISSED** [review]
It's OK to ignore the user warnings for now (you can use a hadolint ignore comment).

**Comment by lk-iqt** [comment]
@anarkiwi fixed.

**Comment by anarkiwi** [comment]
Great looks like almost there - just two Codacy "suggestions": https://app.codacy.com/gh/IQTLabs/gamutRF/pullRequest?prid=12954047

Binding to all ports within a container is fine because we can override that with Docker (and in fact we need the all ports bind within the container to do any port mapping). The pip version pinning also isn't critical, because we test building all our images and running them, so that if for some reason the build or the test failed due to a poetry change we will pick this up automatically. 

https://github.com/IQTLabs/gamutRF/blob/bc022a968cf730af944ef1b90a8afd29cb8cbfd3/gamutrf/worker.py#L384 shows how to take care of the port bind, and you can add a hadolint comment to disable DL3013.

**Comment by anarkiwi** [comment]
https://github.com/IQTLabs/gamutRF/blob/main/gamutrf/worker.py#L329 shows how to deal with the new codeql pattern.

**Review by anarkiwi — DISMISSED** [review]

**Review by anarkiwi — APPROVED** [review]

**Pull request merged**
