### PR TITLE
Adds a flag to disable Ettus Auto DC offset

### PR DESCRIPTION
**Pull request by robotastic**
By default, the Ettus B200 mini applies a DC offset to help remove the DC Spike. This PR adds an argument for turning off this DC Spike correction.

The flag is:
--disable_ettus_dc_offset

### CODE REVIEW

**Comment by anarkiwi** [comment]
Suggest boolean action style, eg:

    parser.add_argument(
        "--sigmf",
        dest="sigmf",
        default=True,
        action=BooleanOptionalAction,
        help="add sigmf meta file",
    )

Then we get an automatic option for --no-option

Also request a log message with the state of the option as sent to the ettus driver.

**Comment by robotastic** [comment]
I made updates to include those changes. There is now a logging message in ettus_source.py that prints out whether DC Offset is set or not.

When the `--ettus-dc-offset` argument is present the output is:
```bash
gamutrf-1     | 2024-02-01 17:25:56,592 Ettus source configured with Sample Rate: 20480000.0	Center Freq: 700000000.0	Ettus DC Offset enabled: True
```

When the `--no-ettus-dc-offset` argument is present the output is:
```bash
gamutrf-1     | 2024-02-01 17:25:56,592 Ettus source configured with Sample Rate: 20480000.0	Center Freq: 700000000.0	Ettus DC Offset enabled: True
```

The default when neither argument is present is for it to be enabled. The output for this is:
```bash
gamutrf-1     | 2024-02-01 17:26:33,220 Ettus source configured with Sample Rate: 20480000.0	Center Freq: 700000000.0	Ettus DC Offset enabled: True
```

**Comment by anarkiwi** [comment]
Looks like still need to run "black" and this should be able to go in?

**Comment by robotastic** [comment]
All the CI tests are passing!

**Review by anarkiwi — APPROVED** [review]

**Pull request merged**
